#ifndef _MENUDEFINITIONS__H_
#define _MENUDEFINITIONS__H_

enum { ID_ACTION=13, ID_MENU_EXIT=27,
	   ID_BACKSPACE=8, ID_DECREASE=100, ID_INCREASE=102,
	   ID_PREVIOUS_ITEM=101, ID_NEXT_ITEM=103 };

#endif

